---
title: "MT iPVs"
author: "David Hughes"
date: "3/16/2022"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(iPVs)
source("parameters/pfile.sh")
source("load.R")
```


```{r}
mt_data = study_data$study_mt_data
dim(mt_data)
```

## Define the correlation matrix

```{r}
Cmat = cor(mt_data[, -c(1:2)], method = "sp", use = "pairwise.complete.obs")
Cmat[is.na(Cmat)] = 0
```

## TREE CUT 0.8

```{r, warning=FALSE, message=FALSE, error=FALSE}
Dmat = as.dist(1-abs(Cmat))
nj = hclust(Dmat)
k = cutree(nj, h = 0.8)
####

length(k)
length( table(k) )
```

```{r}
i = 0
while( length(k) != length( table(k) ) ){
  i = i +1
  print(i)
  ## What are the K's ?
  ks = unique(k)

  ## Which MTs are independent ?
  k1 = as.numeric( names( which( table(k) == 1 ) ) )
  w = which(k %in% k1)
  pv1 = names(k)[w]
  
  ## Identify the PVs for the clusters
  kn = as.numeric( names( which(table(k) > 1) ) )
  pv = sapply( kn, function(i){
    n = names(which(k == i))
    s = names( sort( apply(Cmat[n,n], 1, sum) , decreasing = TRUE)[1]  )
    return(s)
  })
  
  ## The New PVs
  pvs = c(pv1, pv)
  
  ## New distance Matrix
  New_Cmat = Cmat[pvs, pvs]
  Dmat = as.dist(1-abs(New_Cmat))
  
  ## New tree and tree cut
  nj = hclust(Dmat)
  k = cutree(nj, h = 0.8)
  
  PVs = names(k)
}
```

```{r}
length(k)
```


```{r, fig.width = 17, fig.height = 8}
plot(nj, hang = -1, cex = 0.5)
abline(h = 0.8, col = "red", lwd = 3)
```

```{r, fig.width = 15, fig.height = 8}
## load a needed R package
library(dendextend)

## extract the IDs for your PVs
pv_ids = PVs

## define your tree as a dendrogram
Dmat = as.dist(1-abs(Cmat))
nj = hclust(Dmat)
dend = nj %>% as.dendrogram

## create a vector of colors to color your tree labels
n = labels(dend)
pcol = rep("black", length(n))
w = which(n %in% pv_ids ); pcol[w] = "medium blue"

## redefine elements of dendrogram
dend = dend %>% 
set("labels_cex", 0.25) %>% 
set("labels_col", pcol) %>% 
set("branches_k_color",  value = pcol)

## plot the dendrogram
par(mar=c(11,3,3,2))
dend %>% plot(main = paste0( "FGFP MTs; Me = ", length(pv_ids) ) )
abline(h = 0.8, col = "red", lwd = 3)


```

```{r}
f = paste0(project_results_dir, "figures/MT_dendrogram_0.8.pdf")
pdf(f, width = 20, height = 8)
par(mar=c(11,3,3,2))
dend %>% plot(main = paste0( "FGFP MTs; Me = ", length(pv_ids) ) )
abline(h = 0.8, col = "red", lwd = 3)
dev.off()

```



## TREE CUT 0.5

```{r, warning=FALSE, message=FALSE, error=FALSE}
Dmat = as.dist(1-abs(Cmat))
nj = hclust(Dmat)
k = cutree(nj, h = 0.5)
####

length(k)
length( table(k) )
```

```{r}
i = 0
while( length(k) != length( table(k) ) ){
  i = i +1
  print(i)
  ## What are the K's ?
  ks = unique(k)

  ## Which MTs are independent ?
  k1 = as.numeric( names( which( table(k) == 1 ) ) )
  w = which(k %in% k1)
  pv1 = names(k)[w]
  
  ## Identify the PVs for the clusters
  kn = as.numeric( names( which(table(k) > 1) ) )
  pv = sapply( kn, function(i){
    n = names(which(k == i))
    s = names( sort( apply(Cmat[n,n], 1, sum) , decreasing = TRUE)[1]  )
    return(s)
  })
  
  ## The New PVs
  pvs = c(pv1, pv)
  
  ## New distance Matrix
  New_Cmat = Cmat[pvs, pvs]
  Dmat = as.dist(1-abs(New_Cmat))
  
  ## New tree and tree cut
  nj = hclust(Dmat)
  k = cutree(nj, h = 0.5)
  
  PVs = names(k)
}
```

```{r}
length(k)
```


```{r, fig.width = 17, fig.height = 8}
plot(nj, hang = -1, cex = 0.5)
abline(h = 0.5, col = "red", lwd = 3)
```

```{r, fig.width = 15, fig.height = 8}
## load a needed R package
library(dendextend)

## extract the IDs for your PVs
pv_ids = PVs

## define your tree as a dendrogram
Dmat = as.dist(1-abs(Cmat))
nj = hclust(Dmat)
dend = nj %>% as.dendrogram

## create a vector of colors to color your tree labels
n = labels(dend)
pcol = rep("black", length(n))
w = which(n %in% pv_ids ); pcol[w] = "medium blue"

## redefine elements of dendrogram
dend = dend %>% 
set("labels_cex", 0.25) %>% 
set("labels_col", pcol) %>% 
set("branches_k_color",  value = pcol)

## plot the dendrogram
par(mar=c(11,3,3,2))
dend %>% plot(main = paste0( "FGFP MTs; Me = ", length(pv_ids) ) )
abline(h = 0.5, col = "red", lwd = 3)


```

```{r}
f = paste0(project_results_dir, "figures/MT_dendrogram_0.5.pdf")
pdf(f, width = 20, height = 8)
par(mar=c(11,3,3,2))
dend %>% plot(main = paste0( "FGFP MTs; Me = ", length(pv_ids) ) )
abline(h = 0.5, col = "red", lwd = 3)
dev.off()
```

